name: Model Validate and Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-and-build:
    uses: CBIIT/bento-workflows/.github/workflows/model-test-and-deploy.yml@v1.1.0
    with:
      model_files: |
        bento_model_file.yaml bento_model_properties.yaml
      model_prefix: bento-model
      event_name: ${{ github.event_name }}
    secrets:
      docker_repo: ${{ secrets.REPO }}
      docker_svc: ${{ secrets.RSVC }}
      repo_user: ${{ secrets.REPO_USER }}
      repo_pw: ${{ secrets.REPO_PW }}
